export const routes = {
    register: "/register",
    login: "/",
    verify: "/verify",
    home: "/",
    dashboard: {
        index: "/dashboard",
        assets: "/dashboard/tokens",
        fees: "/dashboard/fees",
        transactions: "/dashboard/transactions",
        wallets: "/dashboard/wallets",
        relays: "/dashboard/relays",
        activities: "/dashboard/activities",
        notifications: "/dashboard/notifications",
        rankings: "/dashboard/rankings",
        users: "/dashboard/users",
        listings: "/dashboard/listings",
        settings: "/dashboard/settings",
        relay: (id: string) => "/dashboard/relay/" + id,
        wallet: (id: string) => "/dashboard/wallet/" + id,
        listing: (id: string) => "/dashboard/listing/" + id,
        user: (id: number) => "/dashboard/users/" + id,
        pending: "/dashboard/pending",
        rejected: "/dashboard/rejected",
        deleted: "/dashboard/deleted",
    },
};
